### ISSUE TITLE
Same results from Ribocode and RiboCode_psite.py on trained data

### ISSUE THREAD

**Issue by ericmalekos** [gxelab/psite_analysis#1]
I have transcriptome data and I extracted the reads of length 27 which showed about 50/50 frame1 and frame2 offset based on the ribocode metaplot QC. I used psite to train and predict and it seems to do a good job, predicting about 50/50 12-nt offset and 11-nt offset, concordant with what is expected from the QC plot.

```
samtools view ../27nt_trained.bam | cut -f14 | sort | uniq -c
47,361 PS:i:10
29,466,308 PS:i:11
21,299,360 PS:i:12
9,570,808 PS:i:14
```

However, I dont think the RiboCode_psite.py script is working as expected as that script and the standard Ribocode command both return the same predictions:

```
RiboCode -a /RiboCode_annot/gencode.v46_GCAcontigs -c 27_standard/metaplots_pre_config.txt -l no -g -o 27_standard/standard 
python3 ../../psite_analysis/src/RiboCode_psite.py -a /RiboCode_annot/gencode.v46_GCAcontigs -c 27_trained/metaplots_pre_config.txt -l no -g -o 27_trained/trained

wc -l */*collapsed.txt
    9890 27_standard/standard_collapsed.txt
    9890 27_trained/trained_collapsed.txt
```

Could it be an issue with my config files? I uses the same for both:

```
metaplots_pre_config.txt
# SampleName    AlignmentFile   Stranded(yes/reverse)   P-siteReadLength        P-siteLocations
27nt_trained.bam      27nt_trained.bam yes     27      11
```

**Comment by mt1022** [comment]
Hi, Eric,

I guess you were running the two ORF prediction commands in the same directory. Let me illustrate why you got such results using the file I generated when addressing another issue you raised in `PSite` repo:

```bash
# create RiboCode annotation
prepare_transcripts -g gencode.v46.annotation.gtf -f GRCh38.primary_assembly.genome.fa -o ribocode_annot
# create a mock config file
python ribocode_config.py SRR15513148_Aligned.toTranscriptome.psite.bam SRR15513148_transcriptome.train.log >SRR15513148.pre_config
# prediction
python RiboCode_psite.py -a ribocode_annot -c SRR15513148.pre_config -l no -g -A CTG,GTG,TTG -o SRR15513148_ribocode_psite
RiboCode -a ribocode_annot -c SRR15513148.pre_config -l no -g -A CTG,GTG,TTG -o SRR15513148_ribocode_default
# remove the temporary hd5 file & rerun
mv SRR15513148_Aligned.toTranscriptome.psite_psites.hd5 SRR15513148_Aligned.toTranscriptome.psite_psites.hd5.bak
RiboCode -a ribocode_annot -c SRR15513148.pre_config -l no -g -A CTG,GTG,TTG -o SRR15513148_ribocode_default2
```
Then, let's check how many lines there are in the three output files:
```bash
wc -l SRR15513148_ribocode_psite.txt
# 90722 SRR15513148_ribocode_psite.txt
wc -l SRR15513148_ribocode_default.txt
# 90722 SRR15513148_ribocode_default.txt
wc -l SRR15513148_ribocode_default2.txt
# 93827 SRR15513148_ribocode_default2.txt
```
As you can see, I run `RiboCode` twice (only the output prefix were changed) but got different results. When I ran `RiboCode_psite.py`, a temporary file hd5 file was created. When I ran `RiboCode`, it found the hd5 file and reused it. So it generated the same output as the PSite-based script. When I removed the hd5 file, the `RiboCode` will calculate P-sites based on offsets provided in the config file rather than using the PS tag produced by PSite. So this time we got different results.

Cheers!
